[package]
name = "space-bevy"
version = "0.1.0"
authors = ["GUTTERTRASH <shagohad@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_flycam = "*"